export type Options = {
  dry?: boolean;
  withSecret?: boolean;
  withPrivateKey?: boolean;
  amount?: string;
  fee?: string;
  burnCap?: string;
  as?: string;
  alias?: string;
  named?: string;
  entry?: string;
  arg?: string;
  iargs?: string;
  argMichelson?: string;
  argJsonMichelson?: string;
  force?: boolean;
  verbose?: boolean;
  init?: string;
  iparameters?: string;
  iparametersMicheline?: string;
  metadata_storage?: string;
  metadata_uri?: string;
  test?: boolean;
  json?: boolean;
  trace?: boolean;
  force_tezos_client?: boolean;
  with_tezos_client?: boolean;
  protocol?: string;
  storage?: string;
  show_tezos_client_command?: boolean;
  input_path?: string;
  output_path?: string;
  taquito_schema?: boolean;
  with_dapp_originate?: boolean;
  network?: string;
  sandbox_exec_address?: string;
  opt_balance?: string;
  opt_source?: string;
  opt_payer?: string;
  opt_self_address?: string;
  opt_now?: string;
  opt_level?: string;
  contract_json?: any;
  storage_json?: string;
  init_obj_mich?: any;
  parameters?: string;
  parametersMicheline?: string;
}

export const emptyOptions : Options = {
   "alias": undefined,
   "amount": undefined,
   "argMichelson": undefined,
   "as": undefined,
   "burnCap": undefined,
   "dry": false,
   "entry": undefined,
   "fee": undefined,
   "force": false,
   "force_tezos_client": false,
   "iargs": undefined,
   "init": undefined,
   "input_path": undefined,
   "iparameters": undefined,
   "iparametersMicheline": undefined,
   "json": false,
   "metadata_storage": undefined,
   "metadata_uri": undefined,
   "named": undefined,
   "network": undefined,
   "opt_balance": undefined,
   "opt_level": undefined,
   "opt_now": undefined,
   "opt_payer": undefined,
   "opt_self_address": undefined,
   "opt_source": undefined,
   "output_path": undefined,
   "protocol": undefined,
   "sandbox_exec_address": undefined,
   "show_tezos_client_command": false,
   "storage": undefined,
   "taquito_schema": undefined,
   "test": false,
   "trace": false,
   "verbose": false,
   "withPrivateKey": false,
   "withSecret": false,
   "with_dapp_originate": false,
   "with_tezos_client": false,
 }
